### ISSUE TITLE
api 명세서 작업하려는데 권한이 없습니다.

### ISSUE THREAD

**Issue by min050410** [2022-RE-CODE/2022-RE-CODE-BackEnd#14]
🐞  Describe
api 명세서 작업하려는데 권한이 없습니다. 명세서 수정 권한을 주시면 감사하겠습니다.

✅ Tasks
- [x] 1. Not Authorized 해결

🙋🏻 할 말

**Comment by wonyongChoi05** [comment]
죄송합니다 이메일 남겨주시면 초대드리겠습니다!

**Comment by wonyongChoi05** [comment]
죄송합니다 ㅠㅠ GitBook은 팀 요금제를 사용해야하네요 Notion으로 다시 만들어 초대드리겠습니다!

**Comment by wonyongChoi05** [comment]
Notion [초대 링크](https://www.notion.so/invite/65c2f76eee0f64f4d03b195e1732d93a9d4f64e9)입니다!

**Comment by wonyongChoi05** [comment]
노션 들어오시면 위 초대링크 삭제부탁드립니다! @min050410

**Comment by min050410** [comment]
min050410@gmail.com
